TRUNCATE TABLE tbl_service;
TRUNCATE TABLE tbl_mantainance_service;
TRUNCATE TABLE tbl_logs;
TRUNCATE TABLE tbl_income_list;
TRUNCATE TABLE tbl_income;
TRUNCATE TABLE tbl_expenditure_type;
TRUNCATE TABLE tbl_expenditure_logs;
TRUNCATE tbl_expenditure;
TRUNCATE TABLE tbl_account_summary;
TRUNCATE TABLE tbl_account_credit;
TRUNCATE TABLE tbl_account_chart;
TRUNCATE TABLE car_capacity;
TRUNCATE TABLE car_brand;
TRUNCATE TABLE driver;
TRUNCATE TABLE route;
TRUNCATE TABLE fuel_type;
TRUNCATE TABLE mantainance;
TRUNCATE TABLE admin;
TRUNCATE route;
TRUNCATE TABLE vehicle;